-- 코드를 입력하세요
WITH FIRST AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) as MAX_FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN FIRST F
ON R.FOOD_TYPE = F.FOOD_TYPE AND R.FAVORITES = F.MAX_FAV
ORDER BY R.FOOD_TYPE DESC;