-- 코드를 작성해주세요
WITH RECURSIVE GENERATION_DATA AS (
SELECT ID, 1 AS GEN
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL

UNION ALL

SELECT C.ID, P.GEN+1
FROM ECOLI_DATA C JOIN GENERATION_DATA P
ON C.PARENT_ID = P.ID
)

SELECT COUNT(*) AS COUNT, G.GEN AS GENERATION
FROM GENERATION_DATA G LEFT JOIN ECOLI_DATA E
ON G.ID = E.PARENT_ID
WHERE E.PARENT_ID IS NULL
GROUP BY G.GEN
ORDER BY G.GEN ASC;