SELECT T.FLAVOR
FROM
(
    SELECT F.FLAVOR, F.TOTAL_ORDER AS TOTAL
    FROM FIRST_HALF F
    
    UNION ALL
    
    SELECT J.FLAVOR, SUM(J.TOTAL_ORDER) AS TOTAL
    FROM JULY J
    GROUP BY J.FLAVOR
) AS T
GROUP BY T.FLAVOR
ORDER BY SUM(T.TOTAL) DESC
LIMIT 3;