-- 코드를 작성해주세요
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D, (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
) AS FE
WHERE D.SKILL_CODE & FE.CODE > 0
ORDER BY ID;


