-- 코드를 입력하세요
WITH TOTAL_SALE AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)

SELECT U.USER_ID AS USER_ID, U.NICKNAME AS NICKNAME , T.TOTAL AS TOTAL_SALES
FROM USED_GOODS_USER U
JOIN TOTAL_SALE T
ON U.USER_ID = T.WRITER_ID
ORDER BY TOTAL_SALES;