-- 코드를 작성해주세요
SELECT y.YEAR AS YEAR, 
(y.MAX - e.SIZE_OF_COLONY) AS YEAR_DEV,
e.ID AS ID
FROM ECOLI_DATA e
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX
     FROM ECOLI_DATA
     GROUP BY YEAR(DIFFERENTIATION_DATE)) y
ON YEAR(e.DIFFERENTIATION_DATE) = y.YEAR
ORDER BY YEAR(DIFFERENTIATION_DATE), YEAR_DEV;