-- 코드를 입력하세요
WITH 
oct AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) = 10
),

car AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
)

SELECT DISTINCT c.CAR_ID
FROM oct o
INNER JOIN car c
ON c.CAR_ID = o.CAR_ID
ORDER BY c.CAR_ID DESC;