-- 코드를 작성해주세요
WITH 가장큰물고기 AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) as RN
    FROM FISH_INFO
)

SELECT b.ID as ID, n.FISH_NAME as FISH_NAME, b.LENGTH as LENGTH
FROM 가장큰물고기 as b
JOIN FISH_NAME_INFO as n 
ON b.FISH_TYPE = n.FISH_TYPE
WHERE b.RN = 1
ORDER BY b.ID;