-- 코드를 작성해주세요
SELECT h.DEPT_ID AS DEPT_ID, d.DEPT_NAME_EN AS DEPT_NAME_EN, ROUND(AVG(h.SAL)) AS AVG_SAL
FROM HR_EMPLOYEES h
JOIN HR_DEPARTMENT d
ON h.DEPT_ID = d.DEPT_ID
GROUP BY h.DEPT_ID
ORDER BY AVG_SAL DESC;
