-- 코드를 입력하세요
WITH BEST AS
(
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)
SELECT CONCAT("/home/grep/src/", b.BOARD_ID,"/", FILE_ID,FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE f, BEST b
WHERE f.BOARD_ID = b.BOARD_ID
ORDER BY FILE_ID DESC;