-- 코드를 입력하세요
WITH JEN_SALES AS (
    SELECT BOOK_ID, SUM(SALES) as TOTAL_SALES
    FROM BOOK_SALES
    WHERE MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
)
SELECT b.CATEGORY, SUM(j.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK b 
JOIN JEN_SALES j
ON b.BOOK_ID = j.BOOK_ID
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY;